version: '1'
services:  
  mongo:
      image: mongo:latest
      restart: always
      ports:
        - 27017:27017
      volumes:
        - ./mongo-db-data:/data/db
networks:
  dev-network:
    driver: bridge